Repository aexolate/reachliao, pull requests merged in 2022-06, with the labels that each got.

#45 Added Drawer Navigation Menu
  App.js
  AppDrawer.js
  app.config.js
  babel.config.js
  package-lock.json
  package.json
  src/Menu/MapMenu.js
  src/Menu/SettingsMenu.js
  src/components/SearchbarLocation.js
Labels: core feature, high priority

#51 Basic Directions Feature
  AppDrawer.js
  app.config.js
  package-lock.json
  package.json
  src/Menu/DirectionsMenu.js
  src/Menu/MapMenu.js
  src/utils/WaypointsManager.js
Labels: core feature

#56 Added Customization setting for radius
  App.js
  AppDrawer.js
  package-lock.json
  package.json
  src/Menu/MapMenu.js
  src/Menu/SettingsMenu.js
  src/utils/AsyncStorage.js
Labels: enhancement, core feature

#63 Fix radius not changing after setting
  src/Menu/MapMenu.js
  src/components/RadiusTextInput.js
Labels: bug

#64 Fix multiple bugs
  AppDrawer.js
  package-lock.json
  package.json
  src/Menu/DirectionsMenu.js
  src/Menu/MapMenu.js
  src/Menu/SettingsMenu.js
  src/components/RadiusTextInput.js
  src/utils/AsyncStorage.js
Labels: bug
